<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ExcelTemplate extends Model
{
    protected $guarded = ['id'];
    public $timestamps = false;

    public static function exportOrderFields()
    {
        return [
//            [
//                'index'=>0,
//                'table'=>'order_items',
//                'column'=>'id',
//                'name'=>'ID'
//            ],
            [
                'index'=>1,
                'table'=>'orders',
                'column'=>'order_id',
                'name'=>'订单ID',
                'update'=>0
            ],
            [
                'index'=>2,
                'table'=>'order_items',
                'column'=>'item_id',
                'name'=>'订单商品ID',
                'update'=>0
            ],
            [
                'index'=>3,
                'table'=>'order_items',
                'column'=>'item_name',
                'name'=>'商品名称',
                'update'=>0
            ],
            [
                'index'=>4,
                'table'=>'order_items',
                'column'=>'item_price',
                'name'=>'商品价格',
                'update'=>0
            ],
            [
                'index'=>5,
                'table'=>'order_items',
                'column'=>'quantity',
                'name'=>'购买数量',
                'update'=>0
            ],
            [
                'index'=>6,
                'table'=>'order_items',
                'column'=>'options',
                'name'=>'商品选项',
                'update'=>0
            ],
            [
                'index'=>7,
                'table'=>'order_items',
                'column'=>'item_url',
                'name'=>'商品链接',
                'update'=>0
            ],
            [
                'index'=>8,
                'table'=>'order_items',
                'column'=>'supply_market',
                'name'=>'采购平台',
                'update'=>1
            ],
            [
                'index'=>9,
                'table'=>'order_items',
                'column'=>'supply_url',
                'name'=>'采购商品URL',
                'update'=>1
            ],
            [
                'index'=>10,
                'table'=>'order_items',
                'column'=>'supply_image',
                'name'=>'采购商品图片',
                'update'=>0
            ],
            [
                'index'=>11,
                'table'=>'order_items',
                'column'=>'supply_order_id',
                'name'=>'采购订单ID',
                'update'=>1
            ],
            [
                'index'=>12,
                'table'=>'order_items',
                'column'=>'supply_price',
                'name'=>'采购价格',
                'update'=>1
            ],
            [
                'index'=>13,
                'table'=>'order_items',
                'column'=>'supply_delivery_code',
                'name'=>'快递公司CODE',
                'update'=>1
            ],
            [
                'index'=>14,
                'table'=>'order_items',
                'column'=>'supply_delivery_name',
                'name'=>'快递公司名称',
                'update'=>1
            ],
            [
                'index'=>15,
                'table'=>'order_items',
                'column'=>'supply_delivery_number',
                'name'=>'快递单号',
                'update'=>1
            ],
            [
                'index'=>16,
                'table'=>'order_items',
                'column'=>'shipping_company',
                'name'=>'国际物流公司名称',
                'update'=>1
            ],
            [
                'index'=>17,
                'table'=>'order_items',
                'column'=>'invoice_number',
                'name'=>'国际运单号',
                'update'=>1
            ],
            [
                'index'=>18,
                'table'=>'order_items',
                'column'=>'shipping_default',
                'name'=>'默认国际物流',
                'update'=>1
            ],
            [
                'index'=>19,
                'table'=>'orders',
                'column'=>'zipcode',
                'name'=>'收件人邮编',
                'update'=>0
            ],
            [
                'index'=>20,
                'table'=>'orders',
                'column'=>'country',
                'name'=>'国家',
                'update'=>0
            ],
            [
                'index'=>21,
                'table'=>'orders',
                'column'=>'prefecture',
                'name'=>'都道府県',
                'update'=>0
            ],
            [
                'index'=>22,
                'table'=>'orders',
                'column'=>'city',
                'name'=>'郡市区',
                'update'=>0
            ],
            [
                'index'=>23,
                'table'=>'orders',
                'column'=>'address_1',
                'name'=>'详细地址1',
                'update'=>0
            ],
            [
                'index'=>24,
                'table'=>'orders',
                'column'=>'address_2',
                'name'=>'详细地址2',
                'update'=>0
            ],
            [
                'index'=>25,
                'table'=>'orders',
                'column'=>'name_1',
                'name'=>'收件人姓名[汉字]',
                'update'=>0
            ],
            [
                'index'=>26,
                'table'=>'orders',
                'column'=>'name_2',
                'name'=>'收件人姓名[片假名]',
                'update'=>0
            ],
            [
                'index'=>27,
                'table'=>'orders',
                'column'=>'phone_1',
                'name'=>'收件人电话',
                'update'=>0
            ],
            [
                'index'=>28,
                'table'=>'orders',
                'column'=>'phone_2',
                'name'=>'收件人电话[备用]',
                'update'=>0
            ],
            [
                'index'=>29,
                'table'=>'orders',
                'column'=>'email',
                'name'=>'邮箱地址',
                'update'=>0
            ],
            [
                'index'=>30,
                'table'=>'orders',
                'column'=>'infos',
                'name'=>'订单其他信息',
                'update'=>0
            ],
            [
                'index'=>31,
                'table'=>'orders',
                'column'=>'order_time',
                'name'=>'订单时间',
                'update'=>0
            ],
            [
                'index'=>32,
                'table'=>'order_items',
                'column'=>'item_management_id',
                'name'=>'商品管理ID',
                'update'=>0
            ],
            [
                'index'=>33,
                'table'=>'orders',
                'column'=>'full_address',
                'name'=>'收件人地址',
                'update'=>0
            ],
            [
                'index'=>34,
                'table'=>'order_items',
                'column'=>'item_image_path',
                'name'=>'商品图片',
                'update'=>0
            ],
            [
                'index'=>35,
                'table'=>'shops',
                'column'=>'shop_id',
                'name'=>'店铺ID',
                'update'=>0
            ],
            [
                'index'=>36,
                'table'=>'shops',
                'column'=>'shop_name',
                'name'=>'店铺名称',
                'update'=>0
            ],
            [
                'index'=>37,
                'table'=>'orders',
                'column'=>'remark',
                'name'=>'订单备注',
                'update'=>0
            ],
            [
                'index'=>38,
                'table'=>'order_items',
                'column'=>'infos',
                'name'=>'其他信息',
                'update'=>0
            ],
        ];
    }
}
